### ISSUE TITLE
RuntimeError: in loading state_dict for CrossCompareReranker

### ISSUE THREAD

**Issue by NISH1001** [yuchenlin/LLM-Blender#10]
While directly following the code from the readme, I get the following error:

```
RuntimeError: Error(s) in loading state_dict for CrossCompareReranker:
    Missing key(s) in state_dict: "pretrained_model.embeddings.position_ids"
```

The barebone code:
```python
import llm_blender

blender = llm_blender.Blender()
blender.loadranker("llm-blender/PairRM", device="CPU") # error thrown at during this
```

Appreciate any direction on this. I have the `transformers==4.28.1`

**Comment by yuchenlin** [comment]
Hi, 

I guess this could be a version mismatch issue. Would you please try `pip install transformers==4.35.2`?

I run the following on google colab and it seems to work. We'll update this in the requirements. 

https://colab.research.google.com/drive/1PhgaDF9hVJ064hzm_54ub7AiaM_HrlSE?usp=sharing

**Comment by jdf-prog** [comment]
Yeah, I have installed `transformesr==4.28.1` and also get this error. It should be the problem of transformer version. LLM-Blender should require `transformers>=4.31". I will update this to our env requirements.

Besides, please use `cpu` instead of `CPU` also. Otherwise, there will be a key error. Thanks for the issue.

**Comment by NISH1001** [comment]
@yuchenlin `transformers==4.35.2` works. Thank you.
