### ISSUE TITLE
undefined symbol:  _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

### ISSUE THREAD

**Issue by vermabasu** [yuchenlin/LLM-Blender#15]
Hello, I'm getting error while trying to load pre-trained fuser model in llm_blender.Blender() object. It is giving me this error "undefined symbol: 
_ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE".  Is there any solution for this?
<img width="1152" alt="Screenshot 2024-02-26 at 5 01 35 PM" src="https://github.com/yuchenlin/LLM-Blender/assets/72093386/4cf72da5-4857-4119-8607-8d10c3e41e54">
![Screenshot 2024-02-26 at 5 05 36 PM](https://github.com/yuchenlin/LLM-Blender/assets/72093386/5058ee37-38c6-4f22-b3cb-b28fd58f3e13)
![Screenshot 2024-02-26 at 5 05 43 PM](https://github.com/yuchenlin/LLM-Blender/assets/72093386/588a9549-511e-4543-9769-6a95a7cdb666)

**Comment by jdf-prog** [comment]
Hi @vermabasu I think it's a problem with your flash attention module, and not caused by our blender code.

I encountered this problem before, it seems that the problem is that you have compiled the flash attention and other submodules like "fused_layer_norm` with a torch version that does not match your local cuda version (check `nvcc --version`). 

To solve this, you might need to recompile these flash attention modules on a correct cuda environment.
