### ISSUE TITLE
Why  the matrix M is not Symmetrical along the diagonal?

### ISSUE THREAD

**Issue by MAxx8371** [yuchenlin/LLM-Blender#4]

**Comment by MAxx8371** [comment]
In the paper, it mentions M_{i}^{j} = s_{ij} = s^{i}_{ij} - s^{j}_{ij}. Likely, M_{j}^{i} = s_{ji} = s^{j}_{ij} - s^{i}_{ij}. If it were right, why M_{i}^{j} != -M_{j}^{i}?

**Comment by yuchenlin** [comment]
My understanding is that M_ij and M_ji are different because of the order sensitivity. The inputs are `x+y_i+y_j` for M_ij and `x+y_j+y_i` for M_ji.  @jdf-prog may have a better response.

**Comment by jdf-prog** [comment]
Yeah. I think @yuchenlin has answered the question well. To be more specific, the token_ids of the two inputs `x+y_i+y_j` for M_ij and `x+y_j+y_i` for M_ji will be both added with the potional embeddings before fed to BERT encoders. Since the order of `y_i` and `y_j` is different, the positional embedding added to `y_i` and `y_j` will also be different. And that caused the asymmetry of the matrix. 
One way to make the matric to be symmetrici is to change the potional embedding mannual so that `y_i` and `y_j` will be added  with the same potional embeddings for both input orders. And this could be a future work or direction.

**Comment by jdf-prog** [comment]
And we also have an empirical study in **Appendic C.5** about how "asymmetric" the matrix will be. How often will the two input orders give different comparison results? And we find that the two outputs will be consistent for about 90% of the time. Therefore,  we contend that this extent of "asymmetric" would be acceptable for our research.

**Comment by MAxx8371** [comment]
@jdf-prog @yuchenlin Thank you for your responses. I understand that.  Besides, i have another question that which Q functions are you used in practice. In the paper, it says "We assume multiple Q functions to optimize for, such as BERTScore, BARTScore, etc.".

**Comment by jdf-prog** [comment]
> @jdf-prog @yuchenlin Thank you for your responses. I understand that. Besides, i have another question that which Q functions are you used in practice. In the paper, it says "We assume multiple Q functions to optimize for, such as BERTScore, BARTScore, etc.".

We only use BARTScore for its high correlation with human annotations. We state this in **section 5.1: Model Training**. 
Actually, we have tried using BERTScore, BARTScore, BLEURT jointly and the performance on GPT-Rank is not at good as using BARTScore only. We also conduct an rank correlation analysis on **Table 3**, where BARTScore indeed better correlates to the GPT-Rank. I guess that's why using BARTScore only will give better performance.
